# Generated by Django 2.1.2 on 2018-12-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tfgs', '0001_initial'),
        ('core', '0001_initial'),
        ('tfms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=45, verbose_name='Dni')),
                ('phone', models.CharField(max_length=45, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('tfgs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tfgs.Tfgs', verbose_name='Trabajo fin de grado')),
                ('tfms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tfms.Tfms', verbose_name='Trabajo fin de master')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Userinfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('areas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Areas', verbose_name='Area')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('centers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Centers', verbose_name='Centro')),
                ('departaments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departaments', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Información de usuario',
                'verbose_name_plural': 'Informaciones de usuario',
            },
        ),
    ]
