# Generated by Django 2.1.2 on 2018-11-29 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Empresa'), (0, 'Universidad')], verbose_name='Tipo de proyecto')),
                ('objectives', models.TextField(verbose_name='objectivos')),
                ('methodology', models.TextField(verbose_name='Metodología')),
                ('docs_and_forms', models.TextField(verbose_name='Documentos y formatos de entrega')),
                ('language', models.CharField(max_length=45, verbose_name='Idioma')),
                ('knowledge', models.TextField(blank=True, null=True, verbose_name='Conocimientos requeridos')),
                ('departament_validation', models.BooleanField(null=True, verbose_name='Validación del departamento')),
                ('center_validation', models.BooleanField(null=True, verbose_name='Validación del centro')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('masters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Masters', verbose_name='Master')),
                ('tutor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tutor principal')),
                ('tutor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tutor2', verbose_name='Tutor de apoyo')),
            ],
            options={
                'verbose_name': 'Trabajo final de master',
                'verbose_name_plural': 'Trabajos finales de master',
                'ordering': ['-createdAt'],
            },
        ),
    ]
