# Generated by Django 2.1.2 on 2018-10-30 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField()),
                ('mode', models.PositiveSmallIntegerField()),
                ('is_team', models.BooleanField()),
                ('objectives', models.TextField()),
                ('methodology', models.TextField()),
                ('docs_and_forms', models.TextField()),
                ('language', models.CharField(max_length=45, null=True)),
                ('knowledge', models.TextField(null=True)),
                ('type_projects', models.PositiveSmallIntegerField()),
                ('departament_validation', models.BooleanField()),
                ('center_validation', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('carrers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carrers')),
                ('itineraries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Itineraries')),
                ('mentions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mentions')),
                ('skills', models.ManyToManyField(to='core.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('departament', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='students',
            field=models.ManyToManyField(to='project.Students'),
        ),
        migrations.AddField(
            model_name='projects',
            name='tutor1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='tutor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Tutor2'),
        ),
    ]
